version: "3.8"
services:
  eureka:
    container_name: eureka
    image: eureka:jdk14
    restart: unless-stopped
    build: ./eureka-service
    ports:
      - "8761:8761"
    depends_on:
      - db

  zuul:
    container_name: zuul
    image: zuul:jdk14
    restart: unless-stopped
    build: ./zuul-try-2
    environment:
      PORT: 8762
      EUREKA_HOST: eureka
      EUREKA_PORT: 8761
    ports:
      - "8762:8762"
    depends_on:
      - eureka
      - auth
      - userpanel

  db:
    container_name: db
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 896699
      POSTGRES_USER: postgres
    volumes:
      - ./db/db-data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  auth:
    container_name: auth
    image: auth:jdk14
    restart: unless-stopped
    build: ./authentification
    environment:
      PORT: 8081
      DB_HOST: db
      DB_PORT: 5432
      EUREKA_HOST: eureka
      EUREKA_PORT: 8761
    ports:
      - "8081:8081"
    depends_on:
      - eureka
      - db

  userpanel:
    container_name: userpanel
    image: userpanel:jdk14
    restart: unless-stopped
    build: ./userpanel
    environment:
      PORT: 8082
      DB_HOST: db
      DB_PORT: 5432
      EUREKA_HOST: eureka
      EUREKA_PORT: 8761
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - db

networks:
  default:
    name: "ihatenetworks"
