spring:
  application:
    name: zuul-server

eureka:
  client:
    serviceUrl:
      registerWithEureka: false
      fetchRegistry: true
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    preferIpAddress: true

server:
  port: ${PORT:8762}

zuul:
  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
      stripPrefix: false
      sensitiveHeaders:
    user:
      path: /user/**
      serviceId: user-panel-service
      stripPrefix: false
      sensitiveHeaders:
    admin:
      path: /admin/**
      serviceId: user-panel-service
      stripPrefix: false
      sensitiveHeaders:
    #core:
    #  path: /**
    #  serviceId: user-panel-service
    #  stripPrefix: false